# -*- coding: utf-8 -*-
"""
Configuration file
"""

#Algorithm scraping is FOLLOWER_PER_ACCOUNT^(MAX_SCRAPING_DEEP_LEVEL)


ACCOUNT_USERNAME = "YOUR_IG_USERNAME"
ACCOUNT_PASSWORD = "YOUR_IG_PASSWORD"
FIRST_ACCOUNT_USERNAME = "ACCOUNT_USERNAME_TO_CHECK"

FOLLOWER_PER_ACCOUNT = 10
MAX_SCRAPING_DEEP_LEVEL = 1